<?php

namespace Database\Seeders;

use App\Models\Country;
use Illuminate\Database\Seeder;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $usaStates = [
            "AL" => 'Alabama',
            "AK" => 'Alaska',
            "AZ" => 'Arizona',
            "AR" => 'Arkansas',
            "CA" => 'California',
            "CO" => 'Colorado',
            "CT" => 'Connecticut',
            "DE" => 'Delaware',
            "FL" => 'Florida',
            "GA" => 'Georgia',
            "HI" => 'Hawaii',
            "ID" => 'Idaho',
            "IL" => 'Illinois',
            "IN" => 'Indiana',
            "IA" => 'Iowa',
            "KS" => 'Kansas',
            "KY" => 'Kentucky',
            "LA" => 'Louisiana',
            "ME" => 'Maine',
            "MD" => 'Maryland',
            "MA" => 'Massachusetts',
            "MI" => 'Michigan',
            "MN" => 'Minnesota',
            "MS" => 'Mississippi',
            "MO" => 'Missouri',
            "MT" => 'Montana',
            "NC" => 'North Carolina',
            "ND" => 'North Dakota',
            "NE" => 'Nebraska',
            "NV" => 'Nevada',
            "NH" => 'New Hampshire',
            "NJ" => 'New Jersey',
            "NY" => 'New York',
            "NM" => 'New Mexico',
            "OH" => 'Ohio',
            "OK" => 'Oklahoma',
            "OR" => 'Oregon',
            "PA" => 'Pennsylvania',
            "RI" => 'Rhode Island',
            "SC" => 'South Carolina',
            "SD" => 'South Dakota',
            "TN" => 'Tennessee',
            "TX" => 'Texas',
            "UT" => 'Utah',
            "VT" => 'Vermont',
            "VA" => 'Virginia',
            "WA" => 'Washington',
            "WV" => 'West Virginia',
            "WI" => 'Wisconsin',
            "WY" => 'Wyoming',
        ];

        $australiaStates = [
            'ACT' => 'Australian Capital Territory',
            'NSW' => 'New South Wales',
            'NT'  => 'Northern Territory',
            'QLD' => 'Queensland',
            'SA'  => 'South Australia',
            'TAS' => 'Tasmania',
            'VIC' => 'Victoria',
            'WA'  => 'Western Australia',
        ];

        $canadaStates = [
            'AB' => 'Alberta',
            'BC' => 'British Columbia',
            'MB' => 'Manitoba',
            'NB' => 'New Brunswick',
            'NL' => 'Newfoundland and Labrador',
            'NS' => 'Nova Scotia',
            'NT' => 'Northwest Territories',
            'NU' => 'Nunavut',
            'ON' => 'Ontario',
            'PE' => 'Prince Edward Island',
            'QC' => 'Quebec',
            'SK' => 'Saskatchewan',
            'YT' => 'Yukon',
        ];

        $indiaStates = [
            'AP' => 'Andhra Pradesh',
            'AR' => 'Arunachal Pradesh',
            'AS' => 'Assam',
            'BR' => 'Bihar',
            'CT' => 'Chhattisgarh',
            'GA' => 'Goa',
            'GJ' => 'Gujarat',
            'HR' => 'Haryana',
            'HP' => 'Himachal Pradesh',
            'JH' => 'Jharkhand',
            'KA' => 'Karnataka',
            'KL' => 'Kerala',
            'MP' => 'Madhya Pradesh',
            'MH' => 'Maharashtra',
            'MN' => 'Manipur',
            'ML' => 'Meghalaya',
            'MZ' => 'Mizoram',
            'NL' => 'Nagaland',
            'OR' => 'Odisha',
            'PB' => 'Punjab',
            'RJ' => 'Rajasthan',
            'SK' => 'Sikkim',
            'TN' => 'Tamil Nadu',
            'TG' => 'Telangana',
            'TR' => 'Tripura',
            'UP' => 'Uttar Pradesh',
            'UK' => 'Uttarakhand',
            'WB' => 'West Bengal',
        ];

        $mexicoStates = [
            'AGU' => 'Aguascalientes',
            'BCN' => 'Baja California',
            'BCS' => 'Baja California Sur',
            'CAM' => 'Campeche',
            'CHP' => 'Chiapas',
            'CHH' => 'Chihuahua',
            'COA' => 'Coahuila',
            'COL' => 'Colima',
            'DIF' => 'Ciudad de Mexico',
            'DUR' => 'Durango',
            'GUA' => 'Guanajuato',
            'GRO' => 'Guerrero',
            'HID' => 'Hidalgo',
            'JAL' => 'Jalisco',
            'MEX' => 'Mexico',
            'MIC' => 'Michoacan',
            'MOR' => 'Morelos',
            'NAY' => 'Nayarit',
            'NLE' => 'Nuevo Leon',
            'OAX' => 'Oaxaca',
            'PUE' => 'Puebla',
            'QUE' => 'Queretaro',
            'ROO' => 'Quintana Roo',
            'SLP' => 'San Luis Potosi',
            'SIN' => 'Sinaloa',
            'SON' => 'Sonora',
            'TAB' => 'Tabasco',
            'TAM' => 'Tamaulipas',
            'TLA' => 'Tlaxcala',
            'VER' => 'Veracruz',
            'YUC' => 'Yucatan',
            'ZAC' => 'Zacatecas',
        ];

        $russiaStates = [
            'AD' => 'Adygea',
            'AL' => 'Altai Republic',
            'ALT' => 'Altai Krai',
            'AMU' => 'Amur Oblast',
            'ARK' => 'Arkhangelsk Oblast',
            'AST' => 'Astrakhan Oblast',
            'BA' => 'Bashkortostan',
            'BEL' => 'Belgorod Oblast',
            'BRY' => 'Bryansk Oblast',
            'BU' => 'Buryatia',
            'CE' => 'Chechnya',
            'CHE' => 'Chelyabinsk Oblast',
            'CHU' => 'Chukotka Autonomous Okrug',
            'CU' => 'Chuvashia',
            'DA' => 'Dagestan',
            'IN' => 'Ingushetia',
            'IRK' => 'Irkutsk Oblast',
            'IVA' => 'Ivanovo Oblast',
            'KB' => 'Kabardino-Balkaria',
            'KGD' => 'Kaliningrad Oblast',
            'KL' => 'Kalmykia',
            'KLU' => 'Kaluga Oblast',
            'KAM' => 'Kamchatka Krai',
            'KC' => 'Karachay-Cherkessia',
            'KEM' => 'Kemerovo Oblast',
            'KHA' => 'Khabarovsk Krai',
            'KDA' => 'Krasnodar Krai',
            'KYA' => 'Krasnoyarsk Krai',
            'KGN' => 'Kurgan Oblast',
            'KRS' => 'Kursk Oblast',
            'LEN' => 'Leningrad Oblast',
            'LIP' => 'Lipetsk Oblast',
            'MAG' => 'Magadan Oblast',
            'ME' => 'Mari El',
            'MO' => 'Mordovia',
            'MOS' => 'Moscow Oblast',
            'MOW' => 'Moscow',
            'MUR' => 'Murmansk Oblast',
            'NEN' => 'Nenets Autonomous Okrug',
            'NIZ' => 'Nizhny Novgorod Oblast',
            'NGR' => 'Novgorod Oblast',
            'NVS' => 'Novosibirsk Oblast',
            'OMS' => 'Omsk Oblast',
            'ORE' => 'Orenburg Oblast',
            'ORL' => 'Orel Oblast',
            'PNZ' => 'Penza Oblast',
            'PER' => 'Perm Krai',
            'PRI' => 'Primorsky Krai',
            'PSK' => 'Pskov Oblast',
            'ROS' => 'Rostov Oblast',
            'RYA' => 'Ryazan Oblast',
            'SA' => 'Sakha',
            'SAK' => 'Sakhalin Oblast',
            'SAM' => 'Samara Oblast',
            'SAR' => 'Saratov Oblast',
            'SE' => 'North Ossetia-Alania',
            'SMO' => 'Smolensk Oblast',
            'STA' => 'Stavropol Krai',
            'SVE' => 'Sverdlovsk Oblast',
            'TA' => 'Tambov Oblast',
            'TOM' => 'Tomsk Oblast',
            'TUL' => 'Tula Oblast',
            'TVE' => 'Tver Oblast',
            'TY' => 'Tuva',
            'TYU' => 'Tyumen Oblast',
            'UD' => 'Udmurtia',
            'ULY' => 'Ulyanovsk Oblast',
            'VLG' => 'Vladimir Oblast',
            'VLA' => 'Vologda Oblast',
            'VOR' => 'Voronezh Oblast',
            'YAR' => 'Yaroslavl Oblast',
            'ZAB' => 'Zabaykalsky Krai',
        ];

        $micronesiaStates = [
            'TRK' => 'Chuuk (Truk)',
            'KSA' => 'Kosrae',
            'PNI' => 'Pohnpei',
            'YAP' => 'Yap',
        ];

        $malaysiaStates = [
            'JHR' => 'Johor',
            'KDH' => 'Kedah',
            'KTN' => 'Kelantan',
            'MLK' => 'Melaka',
            'NSN' => 'Negeri Sembilan',
            'PHG' => 'Pahang',
            'PNG' => 'Penang',
            'PRK' => 'Perak',
            'PLS' => 'Perlis',
            'SBH' => 'Sabah',
            'SWK' => 'Sarawak',
            'SGR' => 'Selangor',
            'TRG' => 'Terengganu',
            'KUL' => 'Kuala Lumpur',
            'LBN' => 'Labuan',
            'PJY' => 'Putrajaya',
        ];

        $nigeriaStates = [
            'AB' => 'Abia',
            'AD' => 'Adamawa',
            'AK' => 'Akwa Ibom',
            'AN' => 'Anambra',
            'BA' => 'Bauchi',
            'BY' => 'Bayelsa',
            'BE' => 'Benue',
            'BO' => 'Borno',
            'CR' => 'Cross River',
            'DE' => 'Delta',
            'EB' => 'Ebonyi',
            'ED' => 'Edo',
            'EK' => 'Ekiti',
            'EN' => 'Enugu',
            'GO' => 'Gombe',
            'IM' => 'Imo',
            'JI' => 'Jigawa',
            'KD' => 'Kaduna',
            'KN' => 'Kano',
            'KT' => 'Katsina',
            'KE' => 'Kebbi',
            'KO' => 'Kogi',
            'KW' => 'Kwara',
            'LA' => 'Lagos',
            'NA' => 'Nasarawa',
            'NI' => 'Niger',
            'OG' => 'Ogun',
            'ON' => 'Ondo',
            'OS' => 'Osun',
            'OY' => 'Oyo',
            'PL' => 'Plateau',
            'RI' => 'Rivers',
            'SO' => 'Sokoto',
            'TA' => 'Taraba',
            'YO' => 'Yobe',
            'ZA' => 'Zamfara',
            'FC' => 'Federal Capital Territory (Abuja)',
        ];

        $brazilStates = [
            'AC' => 'Acre',
            'AL' => 'Alagoas',
            'AP' => 'Amapá',
            'AM' => 'Amazonas',
            'BA' => 'Bahia',
            'CE' => 'Ceará',
            'DF' => 'Distrito Federal',
            'ES' => 'Espírito Santo',
            'GO' => 'Goiás',
            'MA' => 'Maranhão',
            'MT' => 'Mato Grosso',
            'MS' => 'Mato Grosso do Sul',
            'MG' => 'Minas Gerais',
            'PA' => 'Pará',
            'PB' => 'Paraíba',
            'PR' => 'Paraná',
            'PE' => 'Pernambuco',
            'PI' => 'Piauí',
            'RJ' => 'Rio de Janeiro',
            'RN' => 'Rio Grande do Norte',
            'RS' => 'Rio Grande do Sul',
            'RO' => 'Rondônia',
            'RR' => 'Roraima',
            'SC' => 'Santa Catarina',
            'SP' => 'São Paulo',
            'SE' => 'Sergipe',
            'TO' => 'Tocantins',
        ];

        $germanyStates = [
            'BW' => 'Baden-Württemberg',
            'BY' => 'Baviera',
            'BE' => 'Berlino',
            'BB' => 'Brandeburgo',
            'HB' => 'Brema',
            'HH' => 'Amburgo',
            'HE' => 'Assia',
            'MV' => 'Meclemburgo-Pomerania Anteriore',
            'NI' => 'Bassa Sassonia',
            'NW' => 'Renania Settentrionale-Vestfalia',
            'RP' => 'Renania-Palatinato',
            'SL' => 'Saarland',
            'SN' => 'Sassonia',
            'ST' => 'Sassonia-Anhalt',
            'SH' => 'Schleswig-Holstein',
            'TH' => 'Turingia',
        ];

        $pakistanStates = [
            'IS' => 'Islamabad Capital Territory',
            'PB' => 'Punjab',
            'SD' => 'Sindh',
            'KP' => 'Khyber Pakhtunkhwa',
            'BA' => 'Balochistan',
            'GB' => 'Gilgit-Baltistan',
            'JK' => 'Azad Jammu and Kashmir',
        ];

        $switzerlandStates = [
            'AG' => 'Argovia',
            'AR' => 'Appenzello Esterno',
            'AI' => 'Appenzello Interno',
            'BL' => 'Basilea Campagna',
            'BS' => 'Basilea Città',
            'BE' => 'Berna',
            'FR' => 'Friburgo',
            'GE' => 'Ginevra',
            'GL' => 'Glarona',
            'GR' => 'Grigioni',
            'JU' => 'Giura',
            'LU' => 'Lucerna',
            'NE' => 'Neuchâtel',
            'NW' => 'Nidvaldo',
            'OW' => 'Obvaldo',
            'SG' => 'San Gallo',
            'SH' => 'Sciaffusa',
            'SZ' => 'Svitto',
            'SO' => 'Soletta',
            'TG' => 'Turgovia',
            'TI' => 'Ticino',
            'UR' => 'Uri',
            'VD' => 'Vaud',
            'VS' => 'Vallese',
            'ZG' => 'Zugo',
            'ZH' => 'Zurigo',
        ];

        $countries = [
            ['code' => 'af', 'name' => 'Afghanistan', 'states' => null],
            ['code' => 'al', 'name' => 'Albania', 'states' => null],
            ['code' => 'dz', 'name' => 'Algeria', 'states' => null],
            ['code' => 'ad', 'name' => 'Andorra', 'states' => null],
            ['code' => 'ao', 'name' => 'Angola', 'states' => null],
            ['code' => 'ag', 'name' => 'Antigua and Barbuda', 'states' => null],
            ['code' => 'ar', 'name' => 'Argentina', 'states' => null],
            ['code' => 'am', 'name' => 'Armenia', 'states' => null],
            ['code' => 'au', 'name' => 'Australia', 'states' => json_encode($australiaStates)],
            ['code' => 'at', 'name' => 'Austria', 'states' => null],
            ['code' => 'az', 'name' => 'Azerbaijan', 'states' => null],
            ['code' => 'bs', 'name' => 'Bahamas', 'states' => null],
            ['code' => 'bh', 'name' => 'Bahrain', 'states' => null],
            ['code' => 'bd', 'name' => 'Bangladesh', 'states' => null],
            ['code' => 'bb', 'name' => 'Barbados', 'states' => null],
            ['code' => 'by', 'name' => 'Belarus', 'states' => null],
            ['code' => 'be', 'name' => 'Belgium', 'states' => null],
            ['code' => 'bz', 'name' => 'Belize', 'states' => null],
            ['code' => 'bj', 'name' => 'Benin', 'states' => null],
            ['code' => 'bt', 'name' => 'Bhutan', 'states' => null],
            ['code' => 'bo', 'name' => 'Bolivia', 'states' => null],
            ['code' => 'ba', 'name' => 'Bosnia and Herzegovina', 'states' => null],
            ['code' => 'bw', 'name' => 'Botswana', 'states' => null],
            ['code' => 'br', 'name' => 'Brazil', 'states' => json_encode($brazilStates)],
            ['code' => 'bn', 'name' => 'Brunei Darussalam', 'states' => null],
            ['code' => 'bg', 'name' => 'Bulgaria', 'states' => null],
            ['code' => 'bf', 'name' => 'Burkina Faso', 'states' => null],
            ['code' => 'bi', 'name' => 'Burundi', 'states' => null],
            ['code' => 'cv', 'name' => 'Cabo Verde', 'states' => null],
            ['code' => 'kh', 'name' => 'Cambodia', 'states' => null],
            ['code' => 'cm', 'name' => 'Cameroon', 'states' => null],
            ['code' => 'ca', 'name' => 'Canada', 'states' => json_encode($canadaStates)],
            ['code' => 'cf', 'name' => 'Central African Republic', 'states' => null],
            ['code' => 'td', 'name' => 'Chad', 'states' => null],
            ['code' => 'cl', 'name' => 'Chile', 'states' => null],
            ['code' => 'cn', 'name' => 'China', 'states' => null],
            ['code' => 'co', 'name' => 'Colombia', 'states' => null],
            ['code' => 'km', 'name' => 'Comoros', 'states' => null],
            ['code' => 'cg', 'name' => 'Congo', 'states' => null],
            ['code' => 'cd', 'name' => 'Congo (Democratic Republic of the)', 'states' => null],
            ['code' => 'cr', 'name' => 'Costa Rica', 'states' => null],
            ['code' => 'ci', 'name' => 'Côte d\'Ivoire', 'states' => null],
            ['code' => 'hr', 'name' => 'Croatia', 'states' => null],
            ['code' => 'cu', 'name' => 'Cuba', 'states' => null],
            ['code' => 'cy', 'name' => 'Cyprus', 'states' => null],
            ['code' => 'cz', 'name' => 'Czech Republic', 'states' => null],
            ['code' => 'dk', 'name' => 'Denmark', 'states' => null],
            ['code' => 'dj', 'name' => 'Djibouti', 'states' => null],
            ['code' => 'dm', 'name' => 'Dominica', 'states' => null],
            ['code' => 'do', 'name' => 'Dominican Republic', 'states' => null],
            ['code' => 'ec', 'name' => 'Ecuador', 'states' => null],
            ['code' => 'eg', 'name' => 'Egypt', 'states' => null],
            ['code' => 'sv', 'name' => 'El Salvador', 'states' => null],
            ['code' => 'gq', 'name' => 'Equatorial Guinea', 'states' => null],
            ['code' => 'er', 'name' => 'Eritrea', 'states' => null],
            ['code' => 'ee', 'name' => 'Estonia', 'states' => null],
            ['code' => 'sz', 'name' => 'Eswatini', 'states' => null],
            ['code' => 'et', 'name' => 'Ethiopia', 'states' => null],
            ['code' => 'fj', 'name' => 'Fiji', 'states' => null],
            ['code' => 'fi', 'name' => 'Finland', 'states' => null],
            ['code' => 'fr', 'name' => 'France', 'states' => null],
            ['code' => 'ga', 'name' => 'Gabon', 'states' => null],
            ['code' => 'gm', 'name' => 'Gambia', 'states' => null],
            ['code' => 'ge', 'name' => 'Georgia', 'states' => null],
            ['code' => 'de', 'name' => 'Germany', 'states' => json_encode($germanyStates)],
            ['code' => 'gh', 'name' => 'Ghana', 'states' => null],
            ['code' => 'gr', 'name' => 'Greece', 'states' => null],
            ['code' => 'gd', 'name' => 'Grenada', 'states' => null],
            ['code' => 'gt', 'name' => 'Guatemala', 'states' => null],
            ['code' => 'gn', 'name' => 'Guinea', 'states' => null],
            ['code' => 'gw', 'name' => 'Guinea-Bissau', 'states' => null],
            ['code' => 'gy', 'name' => 'Guyana', 'states' => null],
            ['code' => 'ht', 'name' => 'Haiti', 'states' => null],
            ['code' => 'hn', 'name' => 'Honduras', 'states' => null],
            ['code' => 'hu', 'name' => 'Hungary', 'states' => null],
            ['code' => 'is', 'name' => 'Iceland', 'states' => null],
            ['code' => 'in', 'name' => 'India', 'states' => json_encode($indiaStates)],
            ['code' => 'id', 'name' => 'Indonesia', 'states' => null],
            ['code' => 'ir', 'name' => 'Iran', 'states' => null],
            ['code' => 'iq', 'name' => 'Iraq', 'states' => null],
            ['code' => 'ie', 'name' => 'Ireland', 'states' => null],
            ['code' => 'il', 'name' => 'Israel', 'states' => null],
            ['code' => 'it', 'name' => 'Italy', 'states' => null],
            ['code' => 'jm', 'name' => 'Jamaica', 'states' => null],
            ['code' => 'jp', 'name' => 'Japan', 'states' => null],
            ['code' => 'jo', 'name' => 'Jordan', 'states' => null],
            ['code' => 'kz', 'name' => 'Kazakhstan', 'states' => null],
            ['code' => 'ke', 'name' => 'Kenya', 'states' => null],
            ['code' => 'ki', 'name' => 'Kiribati', 'states' => null],
            ['code' => 'la', 'name' => 'Laos', 'states' => null],
            ['code' => 'lv', 'name' => 'Latvia', 'states' => null],
            ['code' => 'lb', 'name' => 'Lebanon', 'states' => null],
            ['code' => 'ls', 'name' => 'Lesotho', 'states' => null],
            ['code' => 'lr', 'name' => 'Liberia', 'states' => null],
            ['code' => 'ly', 'name' => 'Libya', 'states' => null],
            ['code' => 'li', 'name' => 'Liechtenstein', 'states' => null],
            ['code' => 'lt', 'name' => 'Lithuania', 'states' => null],
            ['code' => 'lu', 'name' => 'Luxembourg', 'states' => null],
            ['code' => 'mo', 'name' => 'Macau', 'states' => null],
            ['code' => 'mk', 'name' => 'North Macedonia', 'states' => null],
            ['code' => 'mg', 'name' => 'Madagascar', 'states' => null],
            ['code' => 'mw', 'name' => 'Malawi', 'states' => null],
            ['code' => 'my', 'name' => 'Malaysia', 'states' => json_encode($malaysiaStates)],
            ['code' => 'mv', 'name' => 'Maldives', 'states' => null],
            ['code' => 'ml', 'name' => 'Mali', 'states' => null],
            ['code' => 'mt', 'name' => 'Malta', 'states' => null],
            ['code' => 'mh', 'name' => 'Marshall Islands', 'states' => null],
            ['code' => 'mr', 'name' => 'Mauritania', 'states' => null],
            ['code' => 'mu', 'name' => 'Mauritius', 'states' => null],
            ['code' => 'mx', 'name' => 'Mexico', 'states' => json_encode($mexicoStates)],
            ['code' => 'fm', 'name' => 'Micronesia', 'states' => json_encode($micronesiaStates)],
            ['code' => 'md', 'name' => 'Moldova', 'states' => null],
            ['code' => 'mc', 'name' => 'Monaco', 'states' => null],
            ['code' => 'mn', 'name' => 'Mongolia', 'states' => null],
            ['code' => 'me', 'name' => 'Montenegro', 'states' => null],
            ['code' => 'ma', 'name' => 'Morocco', 'states' => null],
            ['code' => 'mz', 'name' => 'Mozambique', 'states' => null],
            ['code' => 'mm', 'name' => 'Myanmar', 'states' => null],
            ['code' => 'na', 'name' => 'Namibia', 'states' => null],
            ['code' => 'nr', 'name' => 'Nauru', 'states' => null],
            ['code' => 'np', 'name' => 'Nepal', 'states' => null],
            ['code' => 'nl', 'name' => 'Netherlands', 'states' => null],
            ['code' => 'nz', 'name' => 'New Zealand', 'states' => null],
            ['code' => 'ni', 'name' => 'Nicaragua', 'states' => null],
            ['code' => 'ne', 'name' => 'Niger', 'states' => null],
            ['code' => 'ng', 'name' => 'Nigeria', 'states' => json_encode($nigeriaStates)],
            ['code' => 'no', 'name' => 'Norway', 'states' => null],
            ['code' => 'om', 'name' => 'Oman', 'states' => null],
            ['code' => 'pk', 'name' => 'Pakistan', 'states' => json_encode($pakistanStates)],
            ['code' => 'pw', 'name' => 'Palau', 'states' => null],
            ['code' => 'ps', 'name' => 'Palestine', 'states' => null],
            ['code' => 'pa', 'name' => 'Panama', 'states' => null],
            ['code' => 'pg', 'name' => 'Papua New Guinea', 'states' => null],
            ['code' => 'py', 'name' => 'Paraguay', 'states' => null],
            ['code' => 'pe', 'name' => 'Peru', 'states' => null],
            ['code' => 'ph', 'name' => 'Philippines', 'states' => null],
            ['code' => 'pl', 'name' => 'Poland', 'states' => null],
            ['code' => 'pt', 'name' => 'Portugal', 'states' => null],
            ['code' => 'qa', 'name' => 'Qatar', 'states' => null],
            ['code' => 'ro', 'name' => 'Romania', 'states' => null],
            ['code' => 'ru', 'name' => 'Russia', 'states' => json_encode($russiaStates)],
            ['code' => 'rw', 'name' => 'Rwanda', 'states' => null],
            ['code' => 'sa', 'name' => 'Saudi Arabia', 'states' => null],
            ['code' => 'sn', 'name' => 'Senegal', 'states' => null],
            ['code' => 'rs', 'name' => 'Serbia', 'states' => null],
            ['code' => 'sc', 'name' => 'Seychelles', 'states' => null],
            ['code' => 'sl', 'name' => 'Sierra Leone', 'states' => null],
            ['code' => 'sg', 'name' => 'Singapore', 'states' => null],
            ['code' => 'sk', 'name' => 'Slovakia', 'states' => null],
            ['code' => 'si', 'name' => 'Slovenia', 'states' => null],
            ['code' => 'sb', 'name' => 'Solomon Islands', 'states' => null],
            ['code' => 'so', 'name' => 'Somalia', 'states' => null],
            ['code' => 'za', 'name' => 'South Africa', 'states' => null],
            ['code' => 'kr', 'name' => 'South Korea', 'states' => null],
            ['code' => 'ss', 'name' => 'South Sudan', 'states' => null],
            ['code' => 'es', 'name' => 'Spain', 'states' => null],
            ['code' => 'lk', 'name' => 'Sri Lanka', 'states' => null],
            ['code' => 'sd', 'name' => 'Sudan', 'states' => null],
            ['code' => 'sr', 'name' => 'Suriname', 'states' => null],
            ['code' => 'se', 'name' => 'Sweden', 'states' => null],
            ['code' => 'ch', 'name' => 'Switzerland', 'states' => json_encode($switzerlandStates)],
            ['code' => 'sy', 'name' => 'Syria', 'states' => null],
            ['code' => 'tw', 'name' => 'Taiwan', 'states' => null],
            ['code' => 'tj', 'name' => 'Tajikistan', 'states' => null],
            ['code' => 'tz', 'name' => 'Tanzania', 'states' => null],
            ['code' => 'th', 'name' => 'Thailand', 'states' => null],
            ['code' => 'tl', 'name' => 'Timor-Leste', 'states' => null],
            ['code' => 'tg', 'name' => 'Togo', 'states' => null],
            ['code' => 'to', 'name' => 'Tonga', 'states' => null],
            ['code' => 'tt', 'name' => 'Trinidad and Tobago', 'states' => null],
            ['code' => 'tn', 'name' => 'Tunisia', 'states' => null],
            ['code' => 'tr', 'name' => 'Turkey', 'states' => null],
            ['code' => 'tm', 'name' => 'Turkmenistan', 'states' => null],
            ['code' => 'tv', 'name' => 'Tuvalu', 'states' => null],
            ['code' => 'ug', 'name' => 'Uganda', 'states' => null],
            ['code' => 'ua', 'name' => 'Ukraine', 'states' => null],
            ['code' => 'ae', 'name' => 'United Arab Emirates', 'states' => null],
            ['code' => 'gb', 'name' => 'United Kingdom', 'states' => null],
            ['code' => 'uy', 'name' => 'Uruguay', 'states' => null],
            ['code' => 'uz', 'name' => 'Uzbekistan', 'states' => null],
            ['code' => 'VU', 'name' => 'Vanuatu', 'states' => null],
            ['code' => 'VA', 'name' => 'Vatican City', 'states' => null],
            ['code' => 'VE', 'name' => 'Venezuela', 'states' => null],
            ['code' => 'VN', 'name' => 'Vietnam', 'states' => null],
            ['code' => 'YE', 'name' => 'Yemen', 'states' => null],
            ['code' => 'ZM', 'name' => 'Zambia', 'states' => null],
            ['code' => 'ZW', 'name' => 'Zimbabwe', 'states' => null],
            ['code' => 'usa', 'name' => 'United States of America', 'states' => json_encode($usaStates)],
        ];
        Country::insert($countries);
    }
}
