<?php

return [
  'title' => 'Politica di Reso',
  'text' => '<h2 class="text-2xl font-semibold">Diritto di Recesso</h2><p class="text-xl">Se hai acquistato un prodotto sul nostro e-commerce e desideri restituirlo, puoi esercitare il tuo diritto di recesso entro <strong>14 giorni lavorativi</strong> dalla data di ricevimento del prodotto, senza dover fornire alcuna motivazione.</p><p class="text-xl">Per esercitare il diritto di recesso, è necessario:</p><p class="text-xl">Compilare il form sottostante specificando:<ul class="list-disc ml-5"><li>Nome e Cognome</li><li>Numero d\'ordine</li><li>Descrizione del prodotto da restituire</li><li>Data di acquisto e data di ricevimento del prodotto</li></ul></p><p class="text-xl">Attendere la nostra conferma con le istruzioni per la restituzione.</p><h2 class="text-2xl font-semibold">Condizioni per il Reso</h2><ul class="list-disc ml-5"><li>Il prodotto deve essere restituito nelle stesse condizioni in cui è stato ricevuto: non deve essere stato usato, danneggiato, né presentare segni di usura. Deve inoltre essere restituito con l\'imballaggio originale, completo di tutte le etichette e accessori eventualmente inclusi.</li><li>La spedizione per il reso è a carico del cliente, salvo casi di prodotto difettoso o errato, in cui le spese saranno a nostro carico.</li><li>Il prodotto deve essere spedito all\'indirizzo fornito nella nostra conferma di reso.</li></ul><h2 class="text-2xl font-semibold">Rimborsi</h2><ul class="list-disc ml-5"><li>Una volta ricevuto e ispezionato il prodotto, ti informeremo via email dell\'approvazione o del rifiuto del tuo reso.</li><li>In caso di approvazione, il rimborso verrà effettuato entro <strong>14 giorni lavorativi</strong> dalla ricezione del reso, utilizzando lo stesso metodo di pagamento con cui è stato effettuato l\'acquisto.</li></ul>',
  'order_date' => 'Data di acquisto',
  'order_received' => 'Data di ricevimento',
  'description' => 'Descrizione del prodotto',
];
